-- MySQL Script generated by MySQL Workbench
-- Sat 21 May 2016 11:32:03 AM MSK
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';


-- -----------------------------------------------------
-- Schema chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chat` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `chat` ;

-- -----------------------------------------------------
-- Table `chat`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chat`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chat`.`Messages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `text` LONGTEXT NOT NULL,
  `date` DATE NOT NULL,
  `user_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id_idx` (`user_id` ASC)  COMMENT '',
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `chat`.`Users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
PACK_KEYS = DEFAULT;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `chat`.`Users`
-- -----------------------------------------------------
START TRANSACTION;
USE `chat`;
INSERT INTO `chat`.`Users` (`name`) VALUE ('David');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Jack');
INSERT INTO `chat`.`Users` (`name`) VALUES ('John');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Nik');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Angela');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Bill');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Tom');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Pat');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Andrew');
INSERT INTO `chat`.`Users` (`name`) VALUES ('Lisbet');

COMMIT;


-- -----------------------------------------------------
-- Data for table `chat`.`Messages`
-- -----------------------------------------------------
START TRANSACTION;
USE `chat`;
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Hi', '2016-01-22', 1);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Hello', '2016-01-22', 2);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ('Fine, tu, & u?', '2016-02-23', 2);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'How are u?', '2016-02-23', 1);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'How about getting together?', '2016-06-25', 3);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Why not!', '2016-06-25', 1);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Hey guys', '2016-04-09', 2);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ( 'Wazzup', '2016-04-09', 1);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ('Gotta go to school :(', '2016-04-09', 3);
INSERT INTO `chat`.`Messages` (`text`, `date`, `user_id`) VALUES ('Never wanna do it again', '2016-04-09', 2);

COMMIT;

